#!/usr/bin/env bash
# script that configures an Ubuntu server
sudo cp /etc/hosts /etc/hosts.bak

# Remove existing entries for localhost and facebook.com
sudo sed -i '/\slocalhost$/d' /etc/hosts
sudo sed -i '/facebook.com/d' /etc/hosts

# Add new entries
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
